name: Feature Engineering

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  feature-engineering:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install hopsworks pandas scikit-learn lightgbm mlflow jupyter

    - name: Run Feature Engineering Notebook
      run: |
        jupyter nbconvert --to notebook --execute feature_engineering.ipynb --output=feature_engineering_output.ipynb
        # This will execute the notebook and store the output in the new notebook file

    - name: Commit and Push Processed Data (Optional)
      run: |
        git config --global user.name "mahiswar"
        git config --global user.email "desireddy.mahi.2002@gmail.com"
        git add feature_engineering_output.ipynb
        git commit -m "Add processed data for feature engineering"
        git push
