name: Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  model-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install hopsworks pandas scikit-learn lightgbm mlflow jupyter

    - name: Run Model Training Notebook
      run: |
        jupyter nbconvert --to notebook --execute train_model.ipynb --output=model_training_output.ipynb
        # This will execute the notebook and store the output in the new notebook file

    - name: Commit and Push Model (Optional)
      run: |
        git config --global user.name "mahiswar"
        git config --global user.email "desireddy.mahi.2002@gmail.com"
        git add model_training_output.ipynb
        git commit -m "Add trained model"
        git push
